services:
  redis:
    image: "redis:alpine"
    networks:
      - default
  consumer:
    build:
      context: ./backend
      dockerfile: consumer.Dockerfile
    networks:
      - default
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis:6379
      - DOMAIN=zircon.socialcoding.net
    volumes:
      # Mount the AWS credentials file to the container
      - ~/.aws:/root/.aws
    
networks:
  default:
    name: zircon