# This file is the SAM Local Testing Template for our microservice.
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: This is the Auth Service SAM Local Testing Template

Parameters:
  OPENAI_API_KEY:
    Type: String
    Description: OpenAI API Key
  LEMONFOX_API_KEY:
    Type: String
    Description: LemonFox API Key
  REDIS_URL:
    Type: String
    Description: Redis URL
  KALTURA_PARTNER_ID:
    Type: String
    Description: Kaltura Partner ID

Resources:
  JobQueueFunction:
    Type: AWS::Serverless::Function # More info about Function Resource:
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: cmd/Job/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Timeout: 29
      Events:
        CatchAll:
          Type: HttpApi # More info about API Event Source:
          Properties:
            Path: /submitJob
            Method: POST
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OPENAI_API_KEY
          KALTURA_PARTNER_ID: !Ref KALTURA_PARTNER_ID

  TTSGenerationFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: cmd/Subtitles/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Timeout: 30
      Events:
        DynamoDBTTSEvent:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt DynamoDBTable.StreamArn
            BatchSize: 1
            StartingPosition: LATEST
      Environment:
        Variables:
          LEMONFOX_API_KEY: !Ref LEMONFOX_API_KEY

  VideoGenerationFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: cmd/Queue/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Timeout: 30
      Events:
        DynamoDBVideoEvent:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt DynamoDBTable.StreamArn
            BatchSize: 1
            StartingPosition: LATEST
      Environment:
        Variables:
          REDIS_URL: !Ref REDIS_URL

  ExistsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: cmd/Exists/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: HttpApi # More info about API Event Source:
          Properties:
            Path: /exists
            Method: GET

  HealthFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: cmd/Health/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Timeout: 30
      Events:
        CatchAll:
          Type: HttpApi # More info about API Event Source:
          Properties:
            Path: /health
            Method: GET
      Environment:
        Variables:
          REDIS_URL: !Ref REDIS_URL
