# This file is the SAM Local Testing Template for our microservice.
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: This is the Auth Service SAM Local Testing Template

Parameters:
  GOOGLE_CLIENT_ID:
    Type: String
    Description: Google Client ID
  GOOGLE_CLIENT_SECRET:
    Type: String
    Description: Google Client Secret
  JWT_PRIVATE:
    Type: String
    Description: JWT Secret

Resources:
  AuthFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: cmd/Login/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /login
            Method: GET
      Environment:
        Variables:
          GOOGLE_CLIENT_ID: !Ref GOOGLE_CLIENT_ID
          GOOGLE_CLIENT_SECRET: !Ref GOOGLE_CLIENT_SECRET

  CallbackFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: cmd/Callback/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /callback
            Method: GET
      Environment:
        Variables:
          GOOGLE_CLIENT_ID: !Ref GOOGLE_CLIENT_ID
          GOOGLE_CLIENT_SECRET: !Ref GOOGLE_CLIENT_SECRET
          JWT_PRIVATE: !Ref JWT_PRIVATE
